import { atom } from 'nanostores';
import { Database } from '@/types/supabase';

/**
 * Standardized schema layout mirroring all possible execution outputs 
 * within user_progress.saved_payload
 */
export interface ProgressPayload {
  // 1. Used by "form" & general execution metadata targets
  formData?: Record<string, any>;

  // 2. Used strictly by the "simulator" execution type
  aiFeedback?: {
    score: number;
    summary: string;
    strengths: string[];
    improvements: string[];
    suggestedRewrite?: string;
    realWorldExecutionAdvice?: string[];
  };

  // 3. Used strictly by "log_counter" execution components
  counterTracking?: {
    currentCount: number;
    targetCount: number;
    logHistory: Array<{
      timestamp: string;
      meta?: Record<string, any>;
    }>;
  };

  // 4. Used by "action" & "community" validation hooks
  verification?: {
    externalLinkVerified?: boolean;
    communityPostId?: string;
    timestampVerified?: string;
  };

  // 5. The Universal Retrospective Module (Fires for ALL types upon completion)
  retrospective?: {
    questionPrompt: string;       // Plucked straight from playbook metadata_config
    userResponseText?: string;    // Captured via the vanishing sidebar textarea
    aiValidationText?: string;    // Generated by AI Conductor
    isLoggedToJournal: boolean;   // Flips to true when user saves their thought
  };

  // Safe open extension catch-all indexing signature
  [customKey: string]: any;
}

// Bind our strict payload schema safely over Supabase's generic Json type definition
export type ProgressRow = Database['public']['Tables']['user_progress']['Row'] & {
  saved_payload: ProgressPayload;
};

// Unique key structure map capable of looking up entries by their relative scope identifier
export const $progressStore = atom<Record<string, ProgressRow>>({});

/**
 * 1. Universally hydrates the progress state map dictionary from array records.
 * Falls back safely across task_id, quest_id, or mission_id targets to support any item_type.
 */
export function hydrateProgressStore(rows: ProgressRow[]) {
  const initialMap = rows.reduce((acc, row) => {
    // Resolve the active logical tracking string key based on its structural type
    const trackingKey = row.task_id || row.quest_id || row.mission_id;
    if (trackingKey) {
      acc[trackingKey] = row;
    }
    return acc;
  }, {} as Record<string, ProgressRow>);
  
  $progressStore.set(initialMap);
}

/**
 * 2. Multi-tier safe upsert engine. Overwrites or mounts state blocks reactively.
 */
export function setProgressStoreRow(row: ProgressRow) {
  const trackingKey = row.task_id || row.quest_id || row.mission_id;
  
  if (!trackingKey) {
    console.warn("⚠️ Cannot commit row update to store: missing target task_id, quest_id, or mission_id identifier.");
    return;
  }

  const current = $progressStore.get();
  $progressStore.set({
    ...current,
    [trackingKey]: row
  });
}

/**
 * 3. Scope removal helper
 */
export function removeProgressStoreRow(lookupKey: string) {
  const current = $progressStore.get();
  const updated = { ...current };
  delete updated[lookupKey];
  $progressStore.set(updated);
}