import { Database } from './supabase'; // Path to your autogenerated database.types.ts

// 1. Extract the raw generated row type directly from Supabase's schema definitions
type BaseProfile = Database['public']['Tables']['profiles']['Row'];

// 2. Define strict contracts for your flexible JSONB metadata containers
export interface MentorMetadata {
  bio?: string;
  about_markdown?: string;
  expertise_tags?: string[];
  company_position?: string;
  calendly_url?: string;
  is_featured?: boolean;
}

export interface ProviderMetadata {
  company_name?: string;
  company_website?: string;
  support_email?: string;
  company_description?: string;
  industry_sector?: string;
}

// 3. Intersect the BaseProfile and override the generic JSONB types with your strict interfaces
export type Profile = Omit<BaseProfile, 'mentor_metadata' | 'provider_metadata'> & {
  mentor_metadata: MentorMetadata;
  provider_metadata: ProviderMetadata;
};